### ISSUE TITLE
templates and css+static

### ISSUE THREAD

**Issue by hellysmile** [modocache/django-generate-scaffold#7]
can you share your sitebase.html, and add to README.md that without sitebase.html, which can be found by django, django-generate-scaffold doesnt work

**Comment by modocache** [comment]
You're the second person to bring up something to do with `sitebase.html`, see [this pull request](https://github.com/modocache/django-generate-scaffold/pull/5) for my response.

Unfortunately, I'm not quite sure what the problem is. Please explain exactly what issues you are experiencing. A pull request which fixes the issue is also welcome.
